<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{{ $model }} Report</title>
	{{-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> --}}
	<style>
		body {
			font-family: "Roboto", sans-serif;
			font-size: 14px;
			line-height: 1.5;
			color: #333;
			/* background-color: #f5f5f5; */
			padding: 0;
		}
		.container {
				margin: 0;
				border: none;
				box-shadow: none;
			}
		.row {
			display: flex;
			align-items: center;
			margin-bottom: 10px;
		}
		.row i {
			font-size: 24px;
			margin-right: 10px;
			color: #0077c2;
		}
		.row span {
			font-size: 16px;
			font-weight: bold;
			color: #333;
		}
		table {
			width: 100%;
			border-collapse: collapse;
			margin-bottom: 0;
		}
		th {
			background-color: #0077c2;
			padding: 10px;
			text-align: left;
			color: #fff;
		}
		td {
			padding: 10px;
			border: none;
			border-bottom: none;
		}
		.total {
			font-weight: bold;
		}
		h2 {
			margin: 0 0 20px;
			font-size: 32px;
			text-align: center;
			color: #0077c2;
		}
		p {
			margin: 0 0 30px;
			font-size: 18px;
			text-align: center;
			color: #333;
		}
		footer {
			text-align: right;
			color: #333;
            position: absolute;
            bottom: 0;
            width: 100%;
		}
		footer p {
			margin: 0;
			font-size: 14px;
			font-style: italic;
		}
		
	</style>
</head>
<body>
    <div class="container">
        <div class="row">
            <span>Start Date: {{ isset($startDate) ? $startDate : 'Not Set' }}</span>
        </div>
        <div class="row">
            <span>End Date: {{ isset($endDate) ? $endDate : 'Not Set' }}</span>
        </div>
        <?php $total = 0; ?>
        @if(isset($data) && count($data) > 0)
            @foreach ($data as $item)
                <?php $total += abs($item->amount); ?>
            @endforeach
        @endif
        <div class="row">
            <span>Total: Ksh {{ $total }}</span>
        </div>
    </div>
    <div class="container">
        <h2>{{ isset($model) ? $model : 'Not Set' }} Report</h2>
        <table>
            <thead>
                <tr>
                    <th>User</th>
                    <th>Transaction Time</th>
                    <th>Amount</th>
                    <th>Title</th>
                </tr>
            </thead>
            <tbody>
            @if(isset($data) && count($data) > 0)
				@foreach ($data as $item)
					<tr>
						<td>{{ isset($item->user) ? $item->user->firstname .' '. $item->user->last : 'User data not available' }}</td>
						<td>{{ isset($item->created_at) ? $item->created_at : 'Not available' }}</td>
						<td>Ksh {{ abs($item->amount) }}</td>
						@php
							$data = json_decode($item->meta);
						@endphp
						<td>{{ isset($data->title) ? $data->title : 'Not available' }}</td>
					</tr>
				@endforeach
			@endif
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="total">Total</td>
                    <td class="total">Ksh {{ $total }}</td>
                </tr>
            </tfoot>
        </table>
        <p>Transactions {{isset($count) ? $count : 0}}</p>
    </div>
    <footer>
        @if(null !== setting('company'))
            <p>This is a report generated by {{setting('company')}}.</p>
        @endif
    </footer>
</body>

</html>

